package commons

const (
	SLV            = "SLV"
	Version        = "1"
	appName        = "slv"
	appDataPathEnv = "SLV_APP_DATA"
	yamlNotice     = "# This file is managed by SLV. DO NOT EDIT THIS FILE MANUALLY.\n"
)
