package commons

const (
	SLV                  = "SLV"
	Version        uint8 = 1
	appName              = "slv"
	appDataPathEnv       = "SLV_APP_DATA"
	slvYamlNotice        = "# This file is managed by SLV. DO NOT EDIT THIS FILE MANUALLY.\n"
)
