# Please ensure that atleast one of ["secretBinding","k8sSecret"] are filled. 
# SLV may not work as expected without a secret key or binding specified.

# The secretBinding String
secretBinding: ""


# The name of the secret in the Kubernetes cluster that contains the secretKey or the secretBinding. 
# The secretKey is to be put inside the key name "SecretKey".
# (or)
# The secretBinding is to be put inside the key name "SecretBinding". 
# Ensure that this exists in the same namespace as the release namespace.
k8sSecret: ""

# Name of the job to run
jobName: "slv-job"

# The image with tag to be used for SLV
# You must ensure that the tag that you use is the same as Chart.Version
# Otherwise, helm will throw an error.
image: ""

# Setting resource constraints for the operator.
resource:
  # Resource limits 
  limits:
    cpu: "250m" 
    memory: "250Mi" 
  # Resource requests 
  requests:
    cpu: "250m" 
    memory: "250Mi" 

# The labels to be set for the Deployment/CronJob/Job
labels: {}

# The pod Labels to be set for SLV pods.
podLabels: {}

# The pod Annotations to be set for SLV pods.
podAnnotations: {}

# The nodeSelector to be set for SLV pods.
nodeSelector: {}

# The affinity to be set for SLV pods.
affinity: {}

# The tolerations to be set for SLV pods.
tolerations: []

# Environment variables to be set for the SLV job.
# Cannot override existing environment variables.
# E.g. - name: AWS_ROLE_ARN
#        value: "arn:aws:iam::123456789012:role/slv-role"
#      - name: SOME_ENV_VAR
#        value: "some-value"
env: {}

# Configuration for the ServiceAccount labels and annotations
serviceAccount:
  # Labels to be added to the ServiceAccount
  # Example:
  # labels:
  #   app.kubernetes.io/name: slv
  #   app.kubernetes.io/instance: slv
  labels: {}

  # Annotations to be added to the ServiceAccount
  # Example:
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/slv-role
  annotations: {}

# The number of times kubernetes must retry the job in case of failure.
# This is only applicable when the mode is set to "job" or "cronjob".
backoffLimit: 4

# The number of seconds after which the job must be deleted after it has finished.
# This is only applicable when the mode is set to "job" or "cronjob".
ttlSecondsAfterFinished: 3600

# When set, the job will be run as a "Cronjob". The field specifies how frequently the cronjob has to run.
schedule: # E.g, "0 * * * *" - Runs at the top of every hour
