{{- if .Values.schedule -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: slv-cronjob
  namespace: {{ .Release.Namespace }}
  labels:
    app: slv-cronjob
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished | default 0 }}
      template:
        metadata:
          name: slv-cronjob
          namespace: {{ .Release.Namespace }}
          labels:
            app: slv-cronjob
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: slv
            {{- if and (.Values.image) (not (hasSuffix .Chart.Version .Values.image)) -}}
            {{- fail (printf "The image tag must be set to the Chart.Version '%s'" .Chart.Version) -}}
            {{- end }}
            image: {{ .Values.image | default (printf "ghcr.io/amagioss/slv:%s" .Chart.AppVersion) }}
            resources:
              {{- toYaml .Values.resource | nindent 14 }}
            env:
              {{- with .Values.env }}
                {{- toYaml . | nindent 14 }}
              {{- end }}
                {{- if ne .Values.k8sSecret ""}}
              - name: SLV_K8S_ENV_SECRET
                value: {{ .Values.k8sSecret }}
                {{- end }}
                {{- if ne .Values.secretBinding "" }}
              - name: SLV_ENV_SECRET_BINDING
                value: {{ .Values.secretBinding }}
                {{- end }}                
              - name: SLV_MODE
                value: "k8s_job"
          restartPolicy: Never
          serviceAccountName: slv-serviceaccount
      backoffLimit: {{ .Values.backoffLimit | default 4 }}
{{- end}}
